### ISSUE TITLE
<details> <summary> 語法無法正確 render

### ISSUE THREAD

**Issue by Justineo** [Justineo/draw#3]
```css
[v-show] { 
  display: none; 
}
```

https://github.com/Justineo/draw/blob/11ab9aeed0ea46b64d5a232c26f8f1519af0a6f1/css/app.css#L139-L141
